#!/usr/bin/env bash
#n to query DNS records for a domain and subdomain

query_dns() {
    local domain=$1
    local subdomain=$2

    # Define subdomains to check if not provided
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    # Loop through subdomains and query DNS records
    for sub in "${subdomains[@]}"; do
        result=$(dig +short "$sub.$domain" | awk '{print $1}')
        if [ -n "$result" ]; then
            echo "The subdomain $sub is a A record and points to $result"
        fi
    done
}

# Main script starts here
if [ $# -eq 0 ]; then
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

domain=$1
subdomain=$2

query_dns "$domain" "$subdomain"

