#!/usr/bin/env bash

# Transfers a file from client to a server using scp

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
filepath="$1"
serverip="$2"
username="$3"
sshkey="$4"

scp -o StrictHostKeyChecking=no -i "$sshkey" "$filepath" "$username@$serverip":~/

