#!/usr/bin/env bash
# Installs Nginx on a webserver

apt-get update -y
apt-get -y install nginx
service nginx start
echo "server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.htm index.html index.nginx-debian.html;
    location / {
    	try_files $uri $uri/ =404;
    }
}" > /etc/nginx/sites-available/default

echo "Hello World!" | /var/www/html/index.html
service nginx restart
