#!/usr/bin/env bash
# Installs Nginx on a webserver

sudo apt-get update -y
sudo apt-get -y install nginx
echo "server {
    listen 80 default_server;
    root/var/www/html;
    location / {
    	index index.htm index.html;
    }
}" > /etc/nginx/sites-available/default

echo "Hello World!" | /var/www/html/index.html
service nginx restart
