#!/usn/bin/env bash
#bash script that configures an Nginx server so that redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i 's/location \/ {/location \/redirect_me {\n\treturn 301 https:\/\/wwww.google.com/' /etc/nginx/sites-available/default
sudo service nginx restart
