#!/usr/bin/env bash
#bash script that configures an Nginx server so that redirect_me
apt-get -y update
apt-get -y install nginx

echo "server {
    listen 80;
    listen [::]:80;

    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/redirect

echo 'Hello World!' > /var/www/html/index.nginx-debian.html
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/
rm /etc/nginx/sites-enabled/default
sudo service nginx restart
