#!/usr/bin/env bash
# installs nginx and with a cutom 404 page
apt-get update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
echo "server {
	listen 80;
	listen [::]:80;

	server_name _;

	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}" > /etc/nginx/sites-available/custom_404
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/
rm /etc/nginx/sites-enabled/default
service nginx restart
