#!/usr/bin/env bash
# installs nginx and with a cutom 404 page
sudo apt-get update
sudo apt-get -y install nginx

echo "server {
	listen 80;
	root /var/www/html;

	server_name _;

	location /redirect_me {
		return 301 https://www.google.com;
	}
	error_page 404 /custom_404.html;
	location / {
		index index.htm index.html;
	}
}" > /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo service nginx restart
