#!/usr/bin/env bash
# script will configure a new server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "server {
    listen 80;
    root /var/www/html
    add_header X-Served-By $HOSTNAME;

    location /redirect_me {
    	return 301 https://www.google.com;
    }
    error_page 404 /cutom_404.html;
    location / {
    	index index.htm index.html;
    }
}" > /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo service nginx start
