#!/usr/bin/env bash
# installs loadbalancer and configure HAproxy

sudo apt-get -y update
sudo apt-get install haproxy

echo "
frontend myfrontend
	bind *:80
	mode http
	default_backend mybackend

backend mybackend
	balance roundrobin
	server 202556-web-01 34.227.101.220:80 check
	server 202556-web-02 52.86.118.253:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
