#!/usr/bin/env bash
#A script for the fizzbuzz
for ((i = 1; i <= 100; i++));do
	if (( i % 3 == 0)) && ((i % 5 == 0));then
		echo "FizzBuzz"
	elif ((i % 3 == 0));then
		echo "Buzz"
	elif ((i % 5 == 0));then
		echo "FizzBUzz"
	else
		echo "$i"
	fi
done
