#!/usr/bin/env bash
#A script to show use of elif in bash
TEXT="Best School"
i=1
while ((i <= 10));do
	if [ "$i" == 4 ]; then
		echo "bad luck"

	elif [ "$i" == 8 ]; then
		echo "good luck"
	else

		echo "$TEXT"
	fi
	((i++))
done
