#!/usr/bin/env bash
# A script involving use of case conditional statement
TEXT="Best School"
i=1
while ((i <= 20));do
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
