#!/usr/bin/env bash
#A script that configures an Ubuntu server with locahost as 127.0.0.2
#Facebook.com resolves to 8.8.8.8
cp /etc/hosts /etc/hosts.old
sed -i 's/localhost[[:space:]]*127.0.0.1/localhost 127.0.0.2/' /etc/hosts.old
sed -i 's/facebook.com[[:space:]]*[^#]*/facebook.com8.8.8.8/' /etc/hosts.old
cp -f /etc/hosts.old /etc/hosts
