#!/usr/bin/env bash
#A script that configures an Ubuntu server with locahost as 127.0.0.2
#Facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.old
echo "127.0.0.2		localhost" > ~/hosts.old
echo "8.8.8.8		facebook.com" >> ~/hosts.old
cp -f ~/hosts.old /etc/hosts
